version: '3.7'

services:
  url-db:
    image: mysql:8.0.29
    container_name: url-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=url-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    restart: always